name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux1_x86_64
    steps:
      - name: Install maturin
        run: pip install maturin>=0.9.0,<0.10
      - name: Install nightly rust
        run: curl --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain nightly
      - name: Build
        run: maturin build